### ISSUE TITLE
System properties not saved in core data when working with offline sync

### ISSUE THREAD

**Issue by antitheos** [Azure/azure-mobile-apps-ios-client#2] opened 2015-11-19 22:57 UTC
Just downloaded azuresdk-iOS-v3.0.0-beta4
Using this version when data is saved in the core data model the system properties are not getting set, they are all nil.

**Comment by phvannor** [comment] 2015-11-19 22:59
What server version are you running?  There was a linked client-server change and the contract is now different.

System columns come back as version (not __version) now, so you may need to update your core data model as well.

**Comment by antitheos** [comment] 2015-11-19 23:01
The server version is  0.3.36.0
So originally the system columns would be saved as ms_updateAt, how should the be name now? are we dropping the ms_ prefix

**Comment by phvannor** [comment] 2015-11-19 23:03
Yes, that logic should no longer be needed (since it was to protect from the _ leading character not being allowed in CoreData)  see the changes to teh QS to support this https://github.com/Azure/azure-mobile-services-quickstarts/blob/MobileApp/client/iOS/ZUMOAPPNAME/ZUMOAPPNAME/QSTodoDataModel.xcdatamodeld/QSTodoDataModel.xcdatamodel/contents

**Comment by antitheos** [comment] 2015-11-19 23:06
Ahhh... makes total sense... let me try real quick... 
Probably need to update the offline sync documentation below because it still says you need add the prefix

https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-ios-get-started-offline-data/#review-core-data

**Comment by antitheos** [comment] 2015-11-19 23:11
@phvannor 
That did the trick, do you want me to mark this issue as closed?

**Comment by phvannor** [comment] 2015-11-20 00:12
@mattchenderson, @lindydonna can we look at docs, and get them updated for these cases?  

Closing actual issue as working as intended when moving to the latest & greatest code base in the current beta for MA.

**Closed by phvannor** 2015-11-20 00:12 UTC
